spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://tadarsh101:SBZySjdODhsJ2RCZ@order-management-system.htuje.mongodb.net/order-management-dev?retryWrites=true&w=majority
